M48
; DRILL file {KiCad 9.0.8} date 2026-07-12T16:09:50-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-12T16:09:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.490
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X105.41Y-96.52
X105.41Y-118.11
T2
X106.37Y-57.5
X106.37Y-77.5
T3
X101.6Y-44.45
X101.6Y-127.0
X147.32Y-44.45
X147.32Y-127.0
M30
