M48
; DRILL file KiCad 10.0.1 date 2026-09-07T23:58:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T23:58:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.845
%
G90
G05
T1
X122.7Y-76.938
X123.4Y-124.1
X191.8Y-123.872
X191.9Y-76.9
T2
X149.1Y-80.3
X178.1Y-80.3
M30
